services:
  web:
    build:
      context: .
      target: dev
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "5173:3000"
    volumes:
      - ./frontend:/usr/src/app
    command: npm run dev -- --hostname 0.0.0.0 --port 3000